services:
  pixi-example:
    image: localhost/prefix-dev/docker-project:latest
    build:
      context: .
      target: install
    command: pixi run dev -h 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./docker_project:/app/docker_project:ro
